### ISSUE TITLE
/close returns an object and closes the transaction

### ISSUE THREAD

**Issue by dropwhile** [wavii/darner#19]
I was trying to `/close` a message but not get the next one yet.

```
stats
STAT queue_job_queue_items 2
STAT queue_job_queue_waiters 0
STAT queue_job_queue_open_transactions 0
END

get job_queue/open
VALUE job_queue 0 32
{"url": "http://www.google.com"}
END

stats
STAT queue_job_queue_items 1
STAT queue_job_queue_waiters 0
STAT queue_job_queue_open_transactions 1
END

get job_queue/close
VALUE job_queue 0 32
{"url": "http://www.google.com"}
END

stats
STAT queue_job_queue_items 0
STAT queue_job_queue_waiters 0
STAT queue_job_queue_open_transactions 0
END
```

It looks like `/close` is returning a message, as well as closing the transaction (and not opening a new transaction like `/close/open` would).

Is this expected behavior?

**Comment by erikfrey** [comment]
Good catch!  Yeah, it's interpreting it as "close the last transaction and also get the next item", which is wrong and not what Kestrel does.  I'll post a test and a fix in the next day or two, thanks.

**Comment by erikfrey** [comment]
@cactus 0132f68e65ad315b07564632ffb62926e65d0eeb ought to do the trick for you.

**Comment by dropwhile** [comment]
Thanks Erik!
