### ISSUE TITLE
Add readme install for homebrew

### ISSUE THREAD

**Issue by henrikbjorn** [wavii/darner#5]
if mxcl/homebrew#14203 gets merged it would be nice to have instructions for homebrew.

**Comment by nova77** [comment]
Most definitely!

**Comment by nova77** [comment]
Whops, closed by mistake. I just wanted to say it's a good idea. :)

**Comment by erikfrey** [comment]
@henrikbjorn thanks for doing that.  I'll update the README once it's merged.

**Comment by erikfrey** [comment]
Fixed via #13.
